### ISSUE TITLE
Release name not set on macOS

### ISSUE THREAD

**Issue by vicr123** [probonopd/uploadtool#53] opened 2019-10-21 09:32 UTC
The bash(?) version that comes on macOS/Travis CI is too old to recognise the substitution on line 45.
![image](https://user-images.githubusercontent.com/7380161/67193817-a92f1f00-f441-11e9-8a60-bcb9c1879d06.png)
This results in the upload tool not setting the release name correctly.

**Comment by probonopd** [comment] 2019-10-22 19:45
Caused by a recent change, https://github.com/probonopd/uploadtool/commit/c2e27fc8d3fdb6c6f71fde0e6c3d2ed3bc0018bc. Since that change introduced a build error and is causing this, I am reverting for now.

**Comment by TheAssassin** [comment] 2019-10-23 23:24
You're not running this script in bash, I bet. bash has supported this syntax since version 4.0, which was released in 2009. That mac is very likely not using a bash as standard shell. You should try with `bash uploadtool.sh` instead of `./uploadtool.sh` or `sh uploadtool.sh`.

In any case, we can replace this bash-ism with a POSIX compliant solution.

The build error was *completely* unrelated to the change, it's more of an issue with the script's method that cannot be fixed (race condition due to lack of mutual exclusive access to resource, in this case the GitHub API). See my explanation here: https://github.com/probonopd/uploadtool/pull/55#issuecomment-545676449

**Comment by vicr123** [comment] 2019-10-23 23:25
macOS still ships with bash 3.2 :(

**Comment by TheAssassin** [comment] 2019-10-23 23:28
That's a shame. In any case, that specific bash-ism has been replaced in #55. The new code works fine in `dash` 0.5.8-2.10.

**Comment by TheAssassin** [comment] 2019-10-23 23:33
Would you mind testing my new version? This way @probonopd hopefully won't revert it again. (Yep, had to make this one, sorry!)

![3e67pr](https://user-images.githubusercontent.com/4503202/67441693-20111700-f5fe-11e9-991a-336d814bfac6.jpg)

Direct link:https://github.com/probonopd/uploadtool/raw/76e2330b548a3e1a71f80dd709b89593c4053e2f/upload.sh

**Comment by vicr123** [comment] 2019-10-24 10:48
Giving it a go now. Will report back in 20 minutes (https://travis-ci.org/vicr123/theSlate/jobs/602262107) :)

**Comment by vicr123** [comment] 2019-10-24 11:21
Looks like it works now :)

**Closed** 2019-10-25 19:57 UTC

**Comment by probonopd** [comment] 2019-10-25 19:59
Merged #55. Please let me know whether all is fine now. Thanks!

**Comment by probonopd** [comment] 2019-11-07 22:56
@TheAssassin why is it still building red now? As per my policy, I revert anything that is red for too long...

**Comment by TheAssassin** [comment] 2019-11-07 22:57
Err... ***what?** Please post a link or anything. I have no clue what you mean.

**Comment by jonaski** [comment] 2019-11-07 23:01
Retrigger  the build for arch two

**Comment by probonopd** [comment] 2019-11-07 23:11
> Err... *what? Please post a link or anything. I have no clue what you mean.

I have a reflex that whenever I see a red badge, to revert to the last commit that had resulted in a green badge. And it seems this macOS thing has resulted in a red badge.

![](https://user-images.githubusercontent.com/2480569/68435727-f20e0400-01b3-11ea-892d-559716689ca0.png)

**Comment by probonopd** [comment] 2019-11-07 23:15
> Retrigger the build for arch two

Indeed it was some intermittent issue only, re-running made it green. At this occasion I saw that the two arches were just a leftover and not needed, so I removed the arch thing. Thanks @jonaski and sorry @TheAssassin and everyone for the interruption.

**Comment by TheAssassin** [comment] 2019-11-07 23:19
Yeah, that's again one of these build failures that is very likely to happen with the not so great build script.

Consider adding a random sleep to your build script, ideally in a range of at least 60 seconds. That'll reduce the chance greatly.
